version: '2'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: 'sift'
      RABBITMQ_DEFAULT_PASS: 'sift'
      RABBITMQ_DEFAULT_VHOST: 'sift'
